apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 4
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
      - name: web
        image: fabricioveronez/bootcamp-conversao-distancia:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  selector:
    app: conversao
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer